### ISSUE TITLE
Smeared particle not null but has 0 four-vector

### ISSUE THREAD

**Issue by osbornjd** [eic/eic-smear#1]
There is a bug that some particles (mostly neutrons, sometimes photons) have a non-nullpointer smeared particle but have a completely 0 four vector, indicating that they should have been labeled as null. Here is an example of some output, where the truth shows "pid, px, py, pz, e" and the smeared shows "px, py, pz, e". This case shows that the photon is at large eta, and probably not within the detector acceptance, so should be just marked as null.

```
Truth  : 22 -0.135898 -0.040381 6.46788 6.46943
Smeared : -0 -0 0 0
```

**Comment by kkauder** [comment]
Latest feedback from Joe is "It looks like these scenarios are caught now when I use the handbook detector and updated libraries." 

Closing
